server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-http-header-size: 80KB
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodie?useSSL=false
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DateSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
mybatis:
  type-aliases-package: net.seehope.foodie.shop.pojo
  mapper-locations: classpath*:mappers/**/*.xml
logging:
  level:
    org.spring: info
    net.seehope: info
#server:
#  port: 8080
#  tomcat:
#    uri-encoding: UTF-8
#    max-http-header-size: 80KB
#spring:
#  datasource: # 数据源的相关配置
#    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
#    driver-class-name: com.mysql.jdbc.Driver          # mysql驱动
#    url: jdbc:mysql://localhost:3306/foodie?useSSL=false
#    username: root
#    password: root
#    hikari:
#      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
#      minimum-idle: 5                 # 最小连接数
#      maximum-pool-size: 20           # 最大连接数
#      auto-commit: true               # 自动提交
#      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
#      pool-name: DateSourceHikariCP     # 连接池名字
#      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
#      connection-test-query: SELECT 1
#  http:  #    spring的响应中文不出现乱码
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true
#mybatis:
#  type-aliases-package: net.seehope.foodie.shop.pojo          # 所有POJO类所在包路径
#  mapper-locations: classpath*:mappers/**/*.xml      # mapper映射文件
#logging:
#  level:
#    org.spring: info
#    net.seehope: info
#cn:
#  mtproject:
#    foodie:
#      allowedOrigins:
#        - http://localhost:9001
#        - http://localhost:9002
    #    redis:
    #      password: 123456
    #      cluster:
    #        nodes:
    #          - 192.168.163.100:6379
    #    port: 6379
    #    host: 192.168.84.100
    #    password: 123456
    #    database: 0
    #    timeout: 5000
    #    sentinel:
    #      master: redis-master
    #      nodes:
    #        - 192.168.84.100:26379
    #        - 192.168.84.101:26379
    #        - 192.168.84.102:26379
    #        - 192.168.84.103:26379
#  cache:
#    redis:
#      time-to-live: 604800
#      cache-null-values: true
#      use-key-prefix: true
#  profiles:
#    active:
#      - dev
#  jmx:
#    enabled: false
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#mapper:
#  not-empty: true
